### ISSUE TITLE
Do you sanitize the strings?

### ISSUE THREAD

**Issue by Billybobbonnet** [mindmup/bootstrap-wysiwyg#193]
Hello,

Everything is in the title, do you sanitize the strings or should it be done using a third party way?

Keep up the good work,

Cheers

**Comment by Garito** [comment]
It doesn't make any sense to sanitize on client side since an attack of man in the middle will bypass this sanitization

Do it on server side or, at least, in the jump before to write your data without any interference possible (meaning when the data riches the final server)

**Comment by Billybobbonnet** [comment]
noted. Thanks for answering :)

2015-04-26 22:15 GMT+02:00 Garito notifications@github.com:
