### ISSUE TITLE
Why this editor add so many redundancy tags when paste text?

### ISSUE THREAD

**Issue by charles-zh** [mindmup/bootstrap-wysiwyg#195]
I just test this editor using paste function, but I found it generates so many tags for every line in the text.
Like : <span style="xxxx">xxxx</span>
This behavior likes Microsoft word, it produces too much "style" in the result and wastes a lot of resource for saving/transferring...

**Comment by gojko** [comment]
that's your browser doing it, not the editor. the editor just uses the built-in pasting inside the browser
