### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by chrisharrison** [mindmup/bootstrap-wysiwyg#52]
If you have a bunch of divs on the page with the same class ( **.rte** for instance), and apply the `.wysiwyg` method to them, they work perfectly with the hotkeys but the buttons don't work.

If however, you apply a div to each one ( **#rte1** **#rte2** etc) it does work. This is OK, and for me I can easily do that programmatically in the flow of my application. But it's not standard and caused a little bit of confusion for me, and perhaps a lot of hair pulling for others.

**Comment by neumachen** [comment]
@makusu how would you do that if you were _cloning_ elements and want to have WYSIWYG enabled on each clone node?

**Comment by makusu** [comment]
@magicalbanana Sorry for late reply. Busy these days.

You basically need to have 2 different IDs for each of the WYSIWYG element.

Please take it with a pinch of salt since my comment was well over 3 years ago.
